/**
 * build.mjs — assembles a loadable MV3 extension in dist/.
 *
 *   node build.mjs           one-shot build
 *   node build.mjs --watch   rebuild bundles on change (static copy runs once)
 *
 * What it does:
 *   1. copies src/ (the existing extension, untouched) into dist/,
 *      minus src/deprecated/;
 *   2. bundles the capture + save entries with esbuild:
 *        extension/content/page-interceptor.js  -> dist/js/page-interceptor.js
 *        extension/content/index.js             -> dist/js/capture.js
 *        extension/background/save-worker.js    -> dist/js/save-worker.js
 *   3. writes dist/manifest.json = src/manifest.json + the two content-script
 *      entries (page-interceptor runs in world:"MAIN") + the "downloads"
 *      permission (plan 04);
 *   4. writes dist/background-wrapper.js = legacy import + save-worker import.
 *
 * src/manifest.json itself is NOT modified — it stays loadable exactly as
 * before; dist/ is the artifact to load unpacked (chrome://extensions).
 */

import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const root = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(root, 'src');
const distDir = path.join(root, 'dist');
const watch = process.argv.includes('--watch');

// The only manifest change this project makes for the capture layer (plan 02):
// two content scripts, both document_start, interceptor in the MAIN world.
const CAPTURE_CONTENT_SCRIPTS = [
  {
    matches: ['*://x.com/*', '*://mobile.x.com/*'],
    js: ['js/page-interceptor.js'],
    run_at: 'document_start',
    world: 'MAIN',
    all_frames: false,
  },
  {
    matches: ['*://x.com/*', '*://mobile.x.com/*'],
    js: ['js/capture.js'],
    run_at: 'document_start',
    all_frames: false,
  },
];

// dist/background-wrapper.js replaces the copied src one: same legacy import
// plus the save-worker (plan 04). src/background-wrapper.js is NOT modified.
const BACKGROUND_WRAPPER = `// generated by build.mjs — do not edit (see src/background-wrapper.js for the original)
try {
    importScripts('js/background.js');
}
catch (error) {
    console.log(error);
}
try {
    importScripts('js/save-worker.js');
}
catch (error) {
    console.log(error);
}
try {
    importScripts('js/request-template.js');
}
catch (error) {
    console.log(error);
}
`;

async function copyStatic() {
  await rm(distDir, { recursive: true, force: true });
  await mkdir(distDir, { recursive: true });
  await cp(srcDir, distDir, {
    recursive: true,
    filter: (source) => !source.includes(`${path.sep}deprecated`),
  });
  const manifest = JSON.parse(await readFile(path.join(srcDir, 'manifest.json'), 'utf8'));
  manifest.content_scripts = [...(manifest.content_scripts ?? []), ...CAPTURE_CONTENT_SCRIPTS];
  // Save layer (plan 04): chrome.downloads needs the "downloads" permission.
  // App link (plan 06): "webRequest" for OBSERVATION-ONLY header capture on
  // the media CDNs (no blocking, no modification — see request-template.js).
  for (const permission of ['downloads', 'webRequest']) {
    if (!(manifest.permissions ?? []).includes(permission)) {
      manifest.permissions = [...(manifest.permissions ?? []), permission];
    }
  }
  await writeFile(path.join(distDir, 'manifest.json'), JSON.stringify(manifest, null, 2));
  await writeFile(path.join(distDir, 'background-wrapper.js'), BACKGROUND_WRAPPER);
}

const bundleOptions = {
  entryPoints: [
    { in: path.join(root, 'extension/content/page-interceptor.js'), out: 'page-interceptor' },
    { in: path.join(root, 'extension/content/index.js'), out: 'capture' },
    { in: path.join(root, 'extension/background/save-worker.js'), out: 'save-worker' },
    { in: path.join(root, 'extension/background/request-template.js'), out: 'request-template' },
  ],
  outdir: path.join(distDir, 'js'),
  bundle: true,
  format: 'iife',
  target: ['chrome111', 'firefox128'],
  sourcemap: false,
  logLevel: 'info',
};

// The companion app (plan 06) runs on plain Node but imports @twmd/core
// (TypeScript), so its entry is bundled too: node app/dist/main.mjs.
// Native/npm deps stay external.
const appBundleOptions = {
  entryPoints: [{ in: path.join(root, 'app/src/main.js'), out: 'main' }],
  outdir: path.join(root, 'app/dist'),
  outExtension: { '.js': '.mjs' },
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: ['node20'],
  external: ['better-sqlite3', 'ws'],
  sourcemap: false,
  logLevel: 'info',
};

await copyStatic();
if (watch) {
  const context = await esbuild.context(bundleOptions);
  await context.watch();
  const appContext = await esbuild.context(appBundleOptions);
  await appContext.watch();
  console.log('watching extension/, app/, and packages/core/ …');
} else {
  await esbuild.build(bundleOptions);
  await esbuild.build(appBundleOptions);
  console.log(`built ${path.relative(root, distDir)}/ — load it unpacked via chrome://extensions`);
  console.log('built app/dist/main.mjs — run with: npm run app');
}
